In [76]:
import pandas as pd
import numpy as np

# Checking the pandas version

In [3]:
#Pandas version

pd.__version__

'2.1.4'

# Importing the dataset

In [4]:
#Importing the dataset
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-09-25 14:58:45--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv’

laptops.csv         100%[===================>] 291.58K  --.-KB/s    in 0.03s   

2024-09-25 14:58:45 (8.20 MB/s) - ‘laptops.csv’ saved [298573/298573]



In [8]:
laptops_df=pd.read_csv('laptops.csv')
laptops_df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

# Counting the total number of records in the dataset

In [15]:
laptops_df.index+=1

In [16]:
laptops_df

Laptop       Status   Brand  \
1     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
2     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
3     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
4     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
5     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2159  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2160  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
1     ExpertBook      Intel Core i5    8      512          SSD       NaN   
2             Go      Intel Celeron    8      256          SSD       NaN   
3     ExpertBook      Intel Core i3    8      256          SSD       NaN   
4         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
5            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2157       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2158       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2159        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2160        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
1       15.6    No      1009.00  
2       15.6    No       299.00  
3       15.6    No       789.00  
4       15.6    No      1199.00  
5       15.6    No       669.01  
...      ...   ...          ...  
2156    17.3    No      2699.99  
2157    17.3    No      2899.99  
2158    17.3    No      3399.99  
2159    13.4   Yes      1899.99  
2160    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [20]:
#Records count

laptops_df.index.size

2160

In [21]:
len(laptops_df)

2160

In [23]:
laptops_df.shape[0]

2160

# Laptop brands

In [24]:
laptops_df

Laptop       Status   Brand  \
1     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
2     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
3     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
4     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
5     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2159  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2160  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
1     ExpertBook      Intel Core i5    8      512          SSD       NaN   
2             Go      Intel Celeron    8      256          SSD       NaN   
3     ExpertBook      Intel Core i3    8      256          SSD       NaN   
4         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
5            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2157       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2158       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2159        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2160        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
1       15.6    No      1009.00  
2       15.6    No       299.00  
3       15.6    No       789.00  
4       15.6    No      1199.00  
5       15.6    No       669.01  
...      ...   ...          ...  
2156    17.3    No      2699.99  
2157    17.3    No      2899.99  
2158    17.3    No      3399.99  
2159    13.4   Yes      1899.99  
2160    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [32]:
laptops_df.Brand.nunique()

27

# Calculating the total number of columns with missing values in the dataset

In [33]:
laptops_df.isnull().sum() #returns a Series

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [52]:
missing_values = laptops_df.isnull().sum()
total=0
# Print names of columns with missing values
for column, count in missing_values.items():
    if count > 0:
      total+=1
      print(f"Column '{column}' has {count} missing values.")
print('\n')
print(f"Hence '{total}' columns with missing values are present in the given dataset ")

Column 'Storage type' has 42 missing values.
Column 'GPU' has 1371 missing values.
Column 'Screen' has 4 missing values.


Hence '3' columns with missing values are present in the given dataset 


# Maximum Final Price


```
What's the maximum final price of Dell notebooks in the dataset?
```

In [35]:
laptops_df.tail()

Laptop       Status  Brand  \
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   
2158  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   
2159  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished  Razer   
2160  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished  Razer   

      Model                CPU  RAM  Storage Storage type       GPU  Screen  \
2156  Blade      Intel Core i7   16     1000          SSD  RTX 3060    17.3   
2157  Blade      Intel Core i7   16     1000          SSD  RTX 3070    17.3   
2158  Blade      Intel Core i7   32     1000          SSD  RTX 3080    17.3   
2159   Book  Intel Evo Core i7   16     1000          SSD       NaN    13.4   
2160   Book  Intel Evo Core i7   16      256          SSD       NaN    13.4   

     Touch  Final Price  
2156    No      2699.99  
2157    No      2899.99  
2158    No      3399.99  
2159   Yes      1899.99  
2160   Yes      1699.99

In [53]:
laptops_df[laptops_df['Brand']=="Dell"]["Final Price"].max()

3936.0

# Median Value Of Screen

In [39]:
laptops_df.head()

Laptop Status   Brand  \
1  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
2  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
3  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
4  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
5  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
1  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
2          Go  Intel Celeron    8      256          SSD       NaN    15.6   
3  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
4      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
5         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
1    No      1009.00  
2    No       299.00  
3    No       789.00  
4    No      1199.00  
5    No       669.01

In [55]:
#Find the median value of Screen column in the dataset.

laptops_df['Screen'].median()

15.6

In [56]:
#Calculate the most frequent value of the same Screen column.

laptops_df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [59]:
#Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.

laptops_df['Screen'].isnull().sum()



4

In [64]:
laptops_df["Screen"]=laptops_df["Screen"].fillna(laptops_df['Screen'].mode()[0])

#Since mode() can return multiple values, using [0] accesses the first mode in the Series.

In [66]:
laptops_df['Screen'].isnull().sum()

0

In [67]:
laptops_df['Screen'].median()

15.6

# Sum Of Weights

In [46]:
laptops_df.columns.tolist()

['Laptop',
 'Status',
 'Brand',
 'Model',
 'CPU',
 'RAM',
 'Storage',
 'Storage type',
 'GPU',
 'Screen',
 'Touch',
 'Final Price']

In [68]:
laptops_df.columns.nunique()

12

In [69]:
# Select all the "Innjoo" laptops from the dataset && Select only columns RAM, Storage, Screen

X=laptops_df[laptops_df['Brand']=="Innjoo"][['RAM', 'Storage', 'Screen']]

In [73]:
X=X.values #Convert to numpy array from data frame , we could even use X.to_numpy()

In [86]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [75]:
#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX

XTX=X.T.dot(X)

In [77]:
#Compute the inverse of XTX
XTX_inv=np.linalg.inv(XTX)

In [79]:
y=np.array([[1100, 1300, 800, 900, 1000, 1100]])

In [80]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w

w=XTX_inv.dot(X.T).dot(y)

ValueError: shapes (3,6) and (1,6) not aligned: 6 (dim 1) != 1 (dim 0)

In [81]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [82]:
XTX.shape

(3, 3)

In [88]:
XTX_inv.shape

(3, 3)

In [83]:
(X.T).shape

(3, 6)

In [84]:
X.T

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [87]:
y.shape

(1, 6)

In [ ]:
#MATRIX MULTIPLICATION n*m = a*b where m==b



In [89]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w

w=XTX_inv.dot(X.T).dot(y.T)

In [90]:
#Sum of all elements in the result w

w.sum()

91.2998806299555